name: Build & Test

on:
  push:
  pull_request:
    branches: [ "main" ]
  # Run tests every day at 00:00 UTC against all Rust toolchains
  schedule:
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Project Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ stable, beta, nightly ]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --workspace --verbose
    - name: Run doc tests
      run: cargo test --workspace --doc --verbose
