name: Build and Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build  --verbose
    - name: Run tests
      run: cargo test --workspace --verbose
    - name: Run tests in docs
      run: cargo test --workspace --doc --verbose
